name: lv3-mission-dev-ci/cd

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-jar
          path: ./build/libs/*SNAPSHOT.jar

  deploy:
    runs-on: [ self-hosted, dev ]
    needs: build
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT: ${{ secrets.JWT }}

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: dev-jar
          path: /home/ubuntu/deploy

      - name: Rename JAR file
        run: |
          cd /home/ubuntu/deploy
          mv *-SNAPSHOT.jar dev-build.jar

      - name: Kill existing process on port 80
        run: |
          sudo fuser -k -n tcp 80 || true

      - name: Start server
        run: |
          cd /home/ubuntu/deploy
          sudo nohup java \
            -Dspring.datasource.username="$DB_USERNAME" \
            -Dspring.datasource.password="$DB_PASSWORD" \
            -Dspring.jwt.key="$JWT" \
            -Dspring.profiles.active=dev \
            -Dserver.port=80 \
            -jar ./dev-build.jar >> output.log 2>&1 &
          sleep 5
          pgrep -f dev-build.jar || (echo "서버 실행 실패" && exit 1)
